{% set name = "metomi-rose" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 12844b09c119b7f8e74e7b8f4f6d44a81ce5d399de820b2d415935af0b01da51

build:
  number: 0
  noarch: python

requirements:
  host:
    - __unix
    - pip
    - python >=3.7
  run:
    - __unix
    - python >=3.7

outputs:
  # base package with only required dependencies
  - name: {{ name }}-base
    build:
      script: python -m pip install . --no-deps --ignore-installed -vv
      noarch: python
    requirements:
      host:
        - __unix
        - pip
        - python >=3.7
      run:
        - __unix
        - python >=3.7
        - aiofiles
        - jinja2 >=2.10.1
        - ldap3
        - metomi-isodatetime >=1!3.0,<1!4.0
        - psutil >=5.6.0
        - python
        - requests
        - sqlalchemy
        - setuptools >=49
        # - tornado (rosie disco is temporally disabled)
    test:
      imports:
        - metomi.rose
        - metomi.rose.macro
      commands:
        - rose --version
        - PAGER=cat rose macro --help
        # test packaging of non-python files
        - rose resource syntax/rose-conf.lang

  # "recommended" package
  # For the next release we should spin `rosa` and `rosie disco` out of this
  - name: {{ name }}
    build:
      script: python -m pip install .[graph] --no-deps --ignore-installed -vv
      noarch: python
    requirements:
      host:
        - __unix
        - pip
        - python >=3.7
      run:
        - __unix
        - python >=3.7
        - {{ pin_subpackage(name + "-base", exact=True) }}
        - pygraphviz >1.0,!=1.8
    test:
      imports:
        - metomi.rose
        - metomi.rose.macro
      commands:
        - rose --version
        - PAGER=cat rose macro --help
        - PAGER=cat rosie graph --help
        # test packaging of non-python files
        - rose resource syntax/rose-conf.lang

about:
  home: https://github.com/metomi/rose
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING
  summary: A toolkit for writing, editing and running application configurations.
  doc_url: http://metomi.github.io/rose
  dev_url: https://github.com/metomi/rose

extra:
  recipe-maintainers:
    - oliver-sanders
    - wxtim
    - datamel
    - metronnie
