{% set name = "metomi-rose" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 60fc4a3ebd6be9f2c96c36307cd40b99f7aaaccabfbb9a0168adbf55fd45ea3b

build:
  number: 0
  noarch: python

requirements:
  host:
    - __unix
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - __unix
    - python >={{ python_min }}

outputs:
  # base package with only required dependencies
  - name: {{ name }}-base
    build:
      script: python -m pip install . --no-deps --ignore-installed -vv
      noarch: python
    requirements:
      host:
        - __unix
        - pip
        - python {{ python_min }}
        - setuptools
      run:
        - __unix
        - python >={{ python_min }}
        - aiofiles
        - jinja2 >=2.10.1
        - keyring >=23
        - ldap3
        - metomi-isodatetime >=1!3.0,<1!4.0
        - psutil >=5.6.0
        - requests
        - sqlalchemy >=1,<2
        # - tornado (rosie disco is temporarily disabled)
    test:
      requires:
        - python {{ python_min }}
      imports:
        - metomi.rose
        - metomi.rose.macro
      commands:
        - rose --version
        - PAGER=cat rose macro --help
        # test packaging of non-python files
        - rose resource syntax/rose-conf.lang

  # "recommended" package
  # For the next release we should spin `rosa` and `rosie disco` out of this
  - name: {{ name }}
    build:
      script: python -m pip install .[graph] --no-deps --ignore-installed -vv
      noarch: python
    requirements:
      host:
        - __unix
        - pip
        - python {{ python_min }}
        - setuptools
      run:
        - __unix
        - python >={{ python_min }}
        - {{ pin_subpackage(name + "-base", exact=True) }}
        - pygraphviz >1.0,!=1.8
    test:
      requires:
        - python {{ python_min }}
      imports:
        - metomi.rose
        - metomi.rose.macro
      commands:
        - rose --version
        - PAGER=cat rose macro --help
        - PAGER=cat rosie graph --help
        # test packaging of non-python files
        - rose resource syntax/rose-conf.lang

about:
  home: https://github.com/metomi/rose
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING
  summary: A toolkit for writing, editing and running application configurations.
  doc_url: http://metomi.github.io/rose
  dev_url: https://github.com/metomi/rose

extra:
  recipe-maintainers:
    - oliver-sanders
    - wxtim
    - metronnie
